### ISSUE TITLE
Unable to import in codebase using requires

### ISSUE THREAD

**Issue by icabhinav** [profusion/apollo-federation-file-upload#34]
Hey, I have a codebase where my imports are like:

```
const { ApolloServer, AuthenticationError } = require("apollo-server-express");
const { ApolloGateway, RemoteGraphQLDataSource } = require("@apollo/gateway");
```

So when I try to do `import { ApolloServer } from 'apollo-server';` it breaks. 

I don't know if this is a dumb question, but can I require your library or make it work somehow?

**Comment by cabelitos** [comment]
it looks like that you're using pure JS and not typescript. By default (at least on node 12), node.js uses commonjs and not ES modules. So you can't simple do `import ... from '...'`.

Since those packages are transpiled using typescript you'll probably want to do 
`const { ApolloServer, AuthenticationError } = require("apollo-server-express").default;` (the same for others).

However I wonder why this problem is related to this repo..

**Comment by icabhinav** [comment]
Oh so sorry, I posted the wrong erroring line.

I'm actually trying to do `import FileUploadDataSource from '@profusion/apollo-federation-upload';` which is breaking. So is there a way to do that with require?

**Comment by cabelitos** [comment]
@icabhinav 
`const FileUploadDataSource  = require('@profusion/apollo-federation-upload').default;`

Just like it's stated on my last comment.

**Comment by cabelitos** [comment]
Closing this one, since it's not a problem.
