### ISSUE TITLE
Custom headers get removed with @apollo/gateway@2.0.2

### ISSUE THREAD

**Issue by gandev** [profusion/apollo-federation-file-upload#52]
The last release of @apollo/gateway changed the fetcher lib version and some internals regarding the fetcher. This introduced a problem with this lib. Custom headers are not arriving at the subgraph anymore.

After some investigating it seems that the fetcher of RemoteGraphQLDataSource expects header now as a plain object (not an instance of Headers). If i change this in FileUploadDataSource when calling this.fetcher(...) then it works again.

**Comment by cabelitos** [comment]
Damn, I hate that they keep changing everything without notice. I'll take a look. Sorry for the problem.

**Comment by douglas-wang** [comment]
@cabelitos I have created this PR to fix the issue. Not sure if this passes.

https://github.com/profusion/apollo-federation-file-upload/pull/53

**Comment by Tsymalyi** [comment]
I have same problem.
This problem occures because we send Headers instead of plain object in **this.fetch** function

According to type defenition of [fetch function](https://github.com/apollographql/federation/blob/8c202964a63314791ca2f3b1e414bf1466174972/gateway-js/src/datasources/RemoteGraphQLDataSource.ts#L27) function expects plain object.

```
export interface FetcherRequestInit {
  method?: string;
  // We explicitly do not allow you to pass in a Headers (or FetcherHeaders)
  // object here, because not all implementations recognize "foreign" Headers
  // objects.
  headers?: Record<string, string>;
  body?: string | Buffer;
}
export type Fetcher = (
  url: string,
  // We explicitly do not allow you to pass in a Request object here, because
  // not all implementations recognize "foreign" Request objects.
  init?: FetcherRequestInit,
) => Promise<FetcherResponse>;
```



Also inside [fetch function](https://github.com/npm/make-fetch-happen/blob/c5251f35cb72beb6a0aabcf7dddb66685d6b7872/lib/index.js#L26) wich RemoteGraphQLDataSource uses by default, a spread operator is used
`
      headers: {
        ...defaultOptions.headers,
        ...options.headers,
      },
`

And if we send Header instead of plain object, after spread operation we receive this:

```
{
 Symbol(map): {
   customHeader: "customHeaderValue"
 }
}
```
instead of what we need 
```
{
   customHeader: "customHeaderValue"
 }
```

**Solution is sending to this.fetch function plain object instead of Header.**
_____________________________________________________________________________
**Work around:**
```
class FileUploadDataSource extends ExternalFileUploadDataSource {
  constructor(config: FileUploadDataSourceArgs) {
    super(config);
    const nativeFetcher = this.fetcher;
    const newFetcher: Fetcher = (url, options) => {
      let plainHeaders: Record<string, string> = options.headers;
      if (options?.headers?.raw) {
        const headers: Headers = options.headers as unknown as Headers;
        plainHeaders = Object.fromEntries<string>(headers) as Record<string, string>;
      }
      return nativeFetcher(url, { ...options, headers: plainHeaders });
    };
    this.fetcher = newFetcher;
  }
  }
```

**Comment by barbieri** [comment]
this was merged as #53, please reopen if anything is still broken

**Comment by glasser** [comment]
Thanks. As one of the people behind the change in Gateway: what we learned was that the concept of providing a fetcher that you could pass "an instance of `Headers` to" was essentially impossible. That's because there are many implementations of "fetch", and they each have their own `Headers` class, and many of them detect whether an object is `Headers` or a plain object via an `instanceof` against their own class. This led to fun things like "you can use `make-fetch-happen` v8 but not v10".

The change we made in Gateway v2.0.2 was to move from "we sorta try to support `Headers` and `Request` objects but it's random and unpredictable whether or not they will work" to "no, you only get to send plain objects, and they will definitely work with any implementation". We changed the TypeScript types to match, so assuming you're using TypeScript this should have been pretty clear on upgrade.

Our thought was that this shouldn't be too much of a compatibility issue because we changed all of the callers to pass the simpler type at the same time. It seems we forgot that this could have an impact on custom RemoteGraphQLDataSource subclasses. Hopefully this was easy to detect due to the TS types breaking at compile time, and it looks like the fix wasn't hard? Thanks for making this update!

**Comment by barbieri** [comment]
@glasser thanks. We'll release an update soon, likely tomorrow.

**Comment by glasser** [comment]
I'm updating our changelog to clarify as well: https://github.com/apollographql/federation/pull/1906

**Comment by barbieri** [comment]
@glasser , @douglas-wang could you check #55 and let me know if that works for you?

**Comment by glasser** [comment]
@barbieri I'm not a direct user so I'm not sure what to test.

What I would suggest is you entirely drop your dependencies on `node-fetch` and `apollo-server-env`, which you're only using to create objects that are passed to our fetcher. Then just set up plain objects that you pass to `this.fetcher` without passing through Headers and Request objects. If you still need a Response type I suggest `FetcherResponse` from `@apollo/utils.fetcher`.

**Comment by glasser** [comment]
Lemme try to improve.

**Comment by glasser** [comment]
Hmm. This is actually hard for fundamental reasons. In the same way that the goal of "you can swap in an arbitrary implementation of fetch and it can tell if an object is a Headers or Request" is a somewhat impossible goal, I'm not really sure there's a consistent way that arbitrary implementations of `fetch` can tell that something passed in is a FormData or not.

But you certainly do need to pass FormData to your fetch. So I don't think your class can really fit properly into the "RemoteGraphQLDataSource has a super user-configurable fetcher" paradigm.

My suggestion is that you choose a *specific* implementation of fetch (or other HTTP library) such as make-fetch-happen v10 or undici and you make your library depend on it.  Then, in your constructor, throw an error if the user passes in a `fetcher` option, and instead pass your favorite chosen fetcher to `super`. Also save a copy of the fetcher locally using types specific to your favorite implementation.  Then you should be able to construct FormData objects from that specific implementation and pass it to your saved fetcher. Of course this means that users won't be able to configure the details of fetching, so you will need to provide your own options to let folks configure fetching (eg overriding headers or whatever) in a way that is compatible with your specific library.

(It turns out that "configure fetching by letting people specify their own W3C `fetch` implementation was a better idea in theory than in practice. Ah well.)

**Comment by barbieri** [comment]
@glasser could you check again, I added the commit https://github.com/profusion/apollo-federation-file-upload/pull/55/commits/dee3c37f9522fdb1b18f7c57284e568c415e6990 `fix: simplify types after @apollo/gateway-2.0.4` that does almost that, I blocked `fetcher` at the TypeScript layer (omitted the property) but I'm not creating the fetcher myself, using `RemoteGraphQLDataSource` default.

While it does have its own risk (ie: they could break us by changing that), it's much less riskier than us replicating those lines and then missing some tweaks/improvements in the defaults. So we'll take that risk and in the eventual situation it break we can release a fix or just force make-fetch-happen.

**Comment by TheBit** [comment]
@glasser can you please take a look at the above? It's hard to believe that Apollo Federation still doesn't have a working File Upload solution :( We built a startup on it - and can't go live as we need a working upload with the latest gateway :(

**Comment by glasser** [comment]
Hi, my apologies — this has been on my todo list for a while but a lot (both work and non-work) has been in the way.

For what it's worth, Apollo [does not recommend](https://www.apollographql.com/blog/backend/file-uploads/file-upload-best-practices/) doing uploads directly in GraphQL requests; this was something we believed even before it was made clear that the graphql-upload protocol opens up implementing servers to CSRF attacks unless explicitly prevented (and our [PR to mention this giant security problem in the spec](https://github.com/jaydenseric/graphql-multipart-request-spec/pull/64) has not been merged).  We know some of our users do use this package and so I would like to help get this merged, but I certainly would recommend that you consider moving your uploads out of your GraphQL handler and into something more tailored to uploads.
